name: Conviso AST Scan (Legacy)

on:
  push:
    branches:
      - master

jobs:
  Conviso_Appsec_AST:
    runs-on: ubuntu-latest

   container:
      image: convisoappsec/convisocli:latest

    steps:
      - uses: actions/checkout@v4

      - name: Running Conviso AST
        run: conviso ast run --vulnerability-auto-close
      env:
        CONVISO_API_KEY: ${{ secrets.CONVISO_API_KEY }}
        CONVISO_COMPANY_ID: 442
        CONVISO_API_URL: "https://staging.convisoappsec.com"
        CONVISO_ASSET_NAME: "juice-shop-mfilho" # ajuste para seu asset real
