name: Conviso Security Gate

on:
  push:
    branches: ["master", "main"]
  pull_request:

jobs:
  run-security-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Conviso CLI
        run: |
          curl -fsSL https://downloads.convisoappsec.com/conviso-cli/install.sh -o install.sh
          bash install.sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          ls -l $HOME/.local/bin
          which conviso || true

      - name: Test CLI
        run: conviso --version

      - name: Authenticate
        run: conviso auth login --api-key ${{ secrets.CONVISO_API_KEY }}

      - name: Security Gate
        run: conviso vulnerability assert-security-rules --rules-file security/security-gate.yml
