name: Conviso Security Gate

on:
  push:
    branches: ["master", "main"]
  pull_request:

jobs:
  run-security-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Conviso CLI
        run: pipx install conviso-cli

      - name: Test CLI
        run: conviso --version

      - name: Authenticate CLI
        run: conviso auth login --api-key ${{ secrets.CONVISO_API_KEY }}

      - name: Apply Security Gate
        run: conviso vulnerability assert-security-rules --rules-file security/security-gate.yml
