name: Conviso Security Gate (Staging)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  conviso-ast:
    runs-on: ubuntu-latest

    container:
      image: convisoappsec/convisocli:latest
      env:
        CONVISO_API_KEY: ${{ secrets.CONVISO_API_KEY }}
        CONVISO_COMPANY_ID: 442
        CONVISO_API_URL: "https://staging.convisoappsec.com"
        CONVISO_ASSET_NAME: "juice-shop-mfilho" # ajuste para seu asset real

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fix Git safe directory issue
      run: git config --global --add safe.directory /__w/juice-shop/juice-shop

    - name: Run AST and Security Gate
      run: |
        conviso ast run --vulnerability-auto-close
        conviso vulnerability assert-security-rules --rules-file security/security-gate.yml
